### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by anp369** [jdav-freiburg/locker#4]
Beim Testen ob mit poetry alles klappt, kam folgender Fehler unabhängig davon irgendwann auf, der lässt das ganze Programm abstürzen:

```
Test card 12345                                                                                                                                                                               
Test card 12345                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                            
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/widgets/base.py", line 14, in _fn                                                                                  
    return fn(*args, **kwargs)                                                                                                                                                                
           ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/seil_locker/widgets/main_window.py", line 84, in read_card                                                         
    username = card_db.verify(card_code)                                                                                                                                                      
               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                      
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/card_db.py", line 23, in verify
    with self._lock():                                                                        
         ^^^^^^^^^^^^                                                                                                                                                                         
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__                            
    return next(self.gen)                                                                     
           ^^^^^^^^^^^^^^                                                                     
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/text_db.py", line 25, in _lock
    self._check_update()                                                                                                                                                                      
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/text_db.py", line 50, in _check_update
    if self._path.is_file() and self._path.stat().st_mtime_ns > self._last_changed:           
                                                                ^^^^^^^^^^^^^^^^^^                                                                                                            
AttributeError: 'CardDatabase' object has no attribute '_last_changed'                        
Traceback (most recent call last):                                                            
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/widgets/base.py", line 14, in _fn 
    return fn(*args, **kwargs)                                                                
           ^^^^^^^^^^^^^^^^^^^                                                                
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/seil_locker/widgets/main_window.py", line 84, in read_card
    username = card_db.verify(card_code)                                                      
               ^^^^^^^^^^^^^^^^^^^^^^^^^                                                      
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/card_db.py", line 23, in verify
    with self._lock():                         
         ^^^^^^^^^^^^                          
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__                             
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/text_db.py", line 25, in _lock
    self._check_update()
  File "/home/andi/Documents/jdav-hackathon/git/locker/software/fjaelllada/db/text_db.py", line 50, in _check_update
    if self._path.is_file() and self._path.stat().st_mtime_ns > self._last_changed:            
                                                                ^^^^^^^^^^^^^^^^^^             
AttributeError: 'CardDatabase' object has no attribute '_last_changed'
```

**Comment by anp369** [comment]
Ping @voegtlel
